function C = night6_slow_wave_caveats(W, R)
% NIGHT6_SLOW_WAVE_CAVEATS  What every slow-wave output carries in its provenance.
%
%   C = night6_slow_wave_caveats(W, R)
%
%   W  the settings the call actually used (night6_slow_wave_settings, = params().slow_wave)
%   R  the rate it ran at (night6_slow_wave_rates: name, factors, factor)
%
% The setting text is BUILT from W and R (review 2026-10-10 fix 5), never written out, so it
% says "full rate" at full rate and "decimated x<factor>" when decimated, and names the
% low-pass the call really had. The passband's upper edge in cycles per minute is the
% low-pass cutoff x 60 (her detrend is the only high-pass). RULINGS 2026-10-09 (h) 1-2 and
% (f) 1.
    if isempty(R.factors)
        rate = 'full rate (no decimation)';
    else
        rate = sprintf('decimated x%d (stages %s)', round(R.factor), ...
                       strjoin(arrayfun(@(f) sprintf('%d', f), R.factors, ...
                                        'UniformOutput', false), ' x '));
    end
    if W.lowPassOn
        lp = sprintf('low-pass %g Hz, order %d', W.lowPassCutoff, W.lowPassOrder);
        band = sprintf(['no high-pass (her detrend only), so the passband is effectively ' ...
                        '0-%g cpm'], W.lowPassCutoff * 60);
        wave = sprintf('the %g Hz-filtered wave', W.lowPassCutoff);
    else
        lp = 'no low-pass';
        band = 'no high-pass (her detrend only) and no low-pass';
        wave = 'the smoothed (not low-passed) wave';
    end
    C = struct( ...
        'setting', sprintf(['RULING 2026-10-09 (h) 1: batch_process - %s, %g s smoothing, ' ...
                            '%g s edge, %s, with blankIdx; %s'], lp, W.smoothWindow, ...
                           W.edgeBufferSec, rate, band), ...
        'amplitude', sprintf(['RULING 2026-10-09 (h) 2: slowWaveTimeSeries and the peak ' ...
                              'amplitudes are amplitudes of %s, not the true waveform. Near ' ...
                              'a masked epoch start they are also sensitive at the few-uV ' ...
                              'level to her whole-epoch detrend, at either sampling rate'], ...
                             wave), ...
        'known_properties', {{ ...
            ['RULING 2026-10-09 (f) 1: findpeaks near-ties - two near-equal maxima can swap ' ...
             'which one is the peak (A ANT1 542.9 against 548.0 s; B ANT1 250.6 s); a ' ...
             'property of her peak rule at both rates'], ...
            ['RULING 2026-10-09 (f) 1: rate-window validity flips at the 30 s clean-length ' ...
             'gate - a window near 30 s of clean data can be valid at one rate and not the ' ...
             'other; a property of her rate rule at both rates']}});
end
